components {
  id: "player"
  component: "/game/player.script"
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"player\"\n"
  "mask: \"flower\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 50.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "rivemodel"
  type: "rivemodel"
  data: "scene: \"/assets/player.rivescene\"\n"
  "default_animation: \"Run\"\n"
  "material: \"/defold-rive/assets/rivemodel.material\"\n"
  "artboard: \"Character\"\n"
  ""
}
